version: '2'

services:
  gcds-app:
    image: tiredofit/gcds:latest
    container_name: gcds-app
    volumes:
    - ./logs:/var/log/gcds
    - ./config:/assets/config
    environment:
    - DRY_RUN=TRUE
    - DOMAIN=example.com
    - LOG_LEVEL=ERROR
    - CONFIGFILE=config.xml
    - LOGFILE=gcds-sync.log
    - ZABBIX_HOSTNAME=gcds-app
    - FORCED_AUTH=FALSE
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

